respuesta = "s"
while respuesta == "s":
    print("USUARIO 1")
    usuario1 = input("codigo: "), input("Apellidos y Nombre: ")
    print("Ingrese su pago")
    pago1 = int(input())
    print("Ingresar descuento")
    descu1 = int(input())
    print("Neto a pagar: ", pago1 - descu1)
    print("USUARIO 2")
    usuario2 = input("codigo: "), input("Apellidos y Nombre: ")
    print("Ingrese su pago")
    pago2 = int(input())
    print("Ingresar descuento")
    descu2 = int(input())
    print("Neto a pagar: ", pago2 - descu2)
    print("USUARIO 3")
    usuario3 = input("codigo: "), input("Apellidos y Nombre: ")
    print("Ingrese su pago")
    pago3 = int(input())
    print("Ingresar descuento")
    descu3 = int(input())
    print("Neto a pagar: ", pago3 - descu3)
    print("USUARIO 4")
    usuario4 = input("codigo: "), input("Apellidos y Nombre: ")
    print("Ingrese su pago")
    pago4 = int(input())
    print("Ingresar descuento")
    descu4 = int(input())
    print("Neto a pagar: ", pago4 - descu4)
    print("USUARIO 5")
    usuario5 = input("codigo: "), input("Apellidos y Nombre: ")
    print("Ingrese su pago")
    pago5 = int(input())
    print("Ingresar descuento")
    descu5 = int(input())
    print("Neto a pagar: ", pago5 - descu5)
    print("Desea continuar si(s) o no(n)")
    respuesta = input()