print("Usuario 1")
codigo1 = input()
apel1 = input()
nom1 = input()
pago1 = int(input())
desc1 = int(input())
print("--------------------------------")
print("Usuario 2")
codigo2 = input()
apel2 = input()
nom2 = input()
pago2 = int(input())
desc2 = int(input())
print("--------------------------------")